// Careers listings for /careers. Each role renders a card + a JobPosting schema
// block (prerendered) so Google can surface them. Evergreen roles; datePosted is
// kept stable so the postings do not churn on every build.

export const CAREERS_INTRO =
  "MedXFlow is building the AI agents that run the healthcare revenue cycle - eligibility, prior authorization, coding, claims, denials and collections - backed by certified RCM experts. We hire people who want their work measured in claims paid and denials prevented, not slides. Remote-first across the US, with a bias for ownership and craft.";

export const DATE_POSTED = "2026-08-01";
export const VALID_THROUGH = "2027-08-01";

export const ROLES = [
  {
    slug: "generative-ai-specialist-rcm",
    title: "Generative AI Specialist (Revenue Cycle)",
    team: "AI & Engineering",
    type: "Full-time",
    location: "Remote (US)",
    experience: "4+ years",
    summary: "Design and ship the AI agents that work real revenue cycles, not demos. You own an agent end to end - prompt and tool design, evaluation, guardrails, and the human-escalation loop - against live payer portals and EHRs.",
    responsibilities: [
      "Build production AI agents for eligibility, prior authorization, coding and denials that complete tasks end to end.",
      "Design robust tool-use, retrieval and evaluation harnesses; measure agents on outcomes (claims paid, denials prevented), not vibes.",
      "Own guardrails, auditability and the escalation path so every action is safe, logged and reviewable.",
      "Partner with certified coders and billers to encode real payer rules into agent behavior.",
    ],
    requirements: [
      "Hands-on experience building LLM-based agents or applications in production.",
      "Strong Python and prompt/eval engineering; comfort with tool-use, RAG and structured outputs.",
      "A bias for shipping and measuring; you instrument everything.",
      "Bonus: healthcare, RCM, EDI or claims experience.",
    ],
  },
  {
    slug: "ai-ml-engineer-healthcare",
    title: "AI / ML Engineer (Healthcare)",
    team: "AI & Engineering",
    type: "Full-time",
    location: "Remote (US)",
    experience: "5+ years",
    summary: "Build the models and data pipelines behind the agents: document extraction from EOBs and 835s, denial classification, and the evaluation infrastructure that keeps quality high as we scale.",
    responsibilities: [
      "Build extraction and classification models for remittances, denials and clinical documents.",
      "Own data pipelines and the offline/online evaluation that gates every model change.",
      "Ship low-latency inference services that agents call in real time.",
      "Keep PHI handling HIPAA-compliant at every step of the pipeline.",
    ],
    requirements: [
      "5+ years in ML engineering with production models, not just notebooks.",
      "Strong Python, solid MLOps (serving, monitoring, evaluation).",
      "Experience with document AI, NLP or information extraction.",
      "Bonus: healthcare data (HL7/FHIR, X12 EDI) experience.",
    ],
  },
  {
    slug: "rcm-solutions-architect",
    title: "RCM Solutions Architect",
    team: "Solutions",
    type: "Full-time",
    location: "Remote (US)",
    experience: "8+ years",
    summary: "Translate a practice's revenue cycle into a working MedXFlow deployment. You are the bridge between payer reality and product - scoping workflows, mapping integrations, and owning a clean go-live.",
    responsibilities: [
      "Scope client revenue-cycle workflows and design the agent + integration plan.",
      "Map EHR/PMS integrations (Epic, athenahealth, eClinicalWorks) and payer connectivity.",
      "Run supervised pilots and drive to a measurable go-live against clear KPIs.",
      "Feed real-world payer patterns back to product and engineering.",
    ],
    requirements: [
      "8+ years in RCM, health-IT implementation or solutions engineering.",
      "Deep knowledge of the end-to-end revenue cycle and payer workflows.",
      "Strong client-facing communication; comfortable owning outcomes.",
      "Experience with EHR/PMS integrations and clearinghouses.",
    ],
  },
  {
    slug: "certified-professional-coder-cpc",
    title: "Certified Professional Coder (CPC)",
    team: "Coding",
    type: "Full-time",
    location: "Remote (US)",
    experience: "3+ years",
    summary: "Own coding accuracy at scale. You review and adjudicate the charts our agents flag, encode payer and NCCI rules into the platform, and set the standard the agents are measured against.",
    responsibilities: [
      "Review and finalize complex and high-risk charts across specialties.",
      "Resolve medical-necessity, modifier and NCCI/MUE edits accurately.",
      "Turn recurring coding patterns into rules that improve the agents.",
      "Maintain compliance and audit-ready documentation.",
    ],
    requirements: [
      "Active AAPC CPC certification (CPC-A considered for strong candidates).",
      "3+ years of production medical coding across multiple specialties.",
      "Fluency in CPT, ICD-10-CM, HCPCS, modifiers and NCCI edits.",
      "Sharp eye for medical necessity and documentation gaps.",
    ],
  },
  {
    slug: "certified-billing-coding-specialist-cbcs",
    title: "Certified Billing and Coding Specialist (CBCS)",
    team: "Billing",
    type: "Full-time",
    location: "Remote (US)",
    experience: "2+ years",
    summary: "Keep clean claims going out and cash coming in. You work the full billing lifecycle, catch what agents escalate, and help tighten the front-end so denials never happen.",
    responsibilities: [
      "Scrub, submit and follow up on claims across payers and clearinghouses.",
      "Work front-end rejections and post payments with line-level reconciliation.",
      "Handle escalations from the agents and feed fixes back upstream.",
      "Track clean-claim and first-pass rates and drive them up.",
    ],
    requirements: [
      "NHA CBCS (or equivalent billing/coding) certification.",
      "2+ years in medical billing with real payer and clearinghouse experience.",
      "Comfort with 837/835 workflows and denial reason codes.",
      "Detail-obsessed and process-driven.",
    ],
  },
  {
    slug: "denial-management-specialist",
    title: "Denial Management Specialist",
    team: "RCM Operations",
    type: "Full-time",
    location: "Remote (US)",
    experience: "3+ years",
    summary: "Turn denials into recovered revenue. You work the highest-value denials by root cause, draft the appeals the agents assemble, and push prevention back into eligibility, coding and prior auth.",
    responsibilities: [
      "Categorize denials by CARC/RARC and work them by recoverable value and filing urgency.",
      "Draft and submit appeals and corrected claims with the right documentation.",
      "Identify root-cause patterns and drive upstream prevention.",
      "Hit overturn-rate and recovery targets month over month.",
    ],
    requirements: [
      "3+ years working denials and appeals in medical billing.",
      "Fluency in CARC/RARC codes and payer appeal processes.",
      "Analytical: you find the pattern, not just work the queue.",
      "Bonus: multi-specialty denial experience.",
    ],
  },
  {
    slug: "prior-authorization-specialist",
    title: "Prior Authorization Specialist",
    team: "RCM Operations",
    type: "Full-time",
    location: "Remote (US)",
    experience: "2+ years",
    summary: "Clear authorizations before they hold up care. You handle the exceptions the agents escalate, keep approvals ahead of the schedule, and stop auth-related denials at the source.",
    responsibilities: [
      "Determine auth requirements and submit requests with clinical documentation.",
      "Track authorizations to approval and surface at-risk or expiring cases early.",
      "Work payer portals and phone queues on the exceptions agents cannot close.",
      "Keep auth status accurate and auditable in the record.",
    ],
    requirements: [
      "2+ years in prior authorization or utilization management.",
      "Knowledge of payer auth rules across commercial, Medicare and Medicaid.",
      "Persistent and organized under deadline pressure.",
      "Clear documentation habits.",
    ],
  },
  {
    slug: "provider-credentialing-specialist",
    title: "Provider Credentialing Specialist",
    team: "RCM Operations",
    type: "Full-time",
    location: "Remote (US)",
    experience: "3+ years",
    summary: "Get providers enrolled so every claim can be paid. You run payer enrollment end to end, keep CAQH and PECOS current, and never let a re-credentialing date lapse.",
    responsibilities: [
      "Prepare and submit payer enrollment and credentialing applications across the payer mix.",
      "Maintain CAQH, PECOS and payer profiles; validate NPIs against NPPES.",
      "Track applications to approval and monitor re-credentialing and expirables.",
      "Keep audit-ready records for delegated-credentialing reviews.",
    ],
    requirements: [
      "3+ years in provider credentialing and payer enrollment.",
      "Deep familiarity with CAQH, PECOS, NPPES and payer portals.",
      "Meticulous with deadlines and documentation.",
      "Bonus: CPCS or CPMSM certification.",
    ],
  },
  {
    slug: "ar-follow-up-specialist",
    title: "Accounts Receivable (A/R) Follow-up Specialist",
    team: "RCM Operations",
    type: "Full-time",
    location: "Remote (US)",
    experience: "2+ years",
    summary: "Chase every dollar to resolution. You work aged A/R, catch underpayments against contracted rates, and keep days-in-A/R trending down alongside the agents.",
    responsibilities: [
      "Work aged A/R by payer and dollar value to resolution.",
      "Detect and recover underpayments against contracted rates.",
      "Resolve the follow-up exceptions agents escalate.",
      "Drive days-in-A/R and net collection rate targets.",
    ],
    requirements: [
      "2+ years in A/R follow-up or medical collections.",
      "Comfort reading EOBs/835s and contracted fee schedules.",
      "Tenacious and numbers-driven.",
      "Clear, professional payer communication.",
    ],
  },
  {
    slug: "revenue-cycle-operations-manager",
    title: "Revenue Cycle Operations Manager",
    team: "RCM Operations",
    type: "Full-time",
    location: "Remote (US)",
    experience: "7+ years",
    summary: "Run the human-plus-agent operation. You lead certified billers and coders, own client KPIs, and orchestrate the hand-off between AI agents and your team so nothing falls through.",
    responsibilities: [
      "Lead a team of certified billers, coders and A/R specialists.",
      "Own client performance against clear KPIs and monthly reviews.",
      "Design the agent-plus-human workflow and the escalation model.",
      "Turn operational insight into product and process improvements.",
    ],
    requirements: [
      "7+ years in RCM with team leadership experience.",
      "Command of the full revenue cycle and its KPIs (denial rate, A/R days, clean-claim rate).",
      "Strong people leadership and client-facing communication.",
      "Comfort operating an automation-augmented team.",
    ],
  },
];
